// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 */

package petstoreserver


import (
	"bytes"
	"encoding/json"
)



// SpecialInfo - An order info for a pets from the pet store
type SpecialInfo struct {

	Promotion bool `json:"promotion,omitempty"`

	RequireTest string `json:"requireTest"`

	Type string `json:"type,omitempty"`
}
type _SpecialInfo SpecialInfo

// UnmarshalJSON validates required property keys then unmarshals into SpecialInfo
func (o *SpecialInfo) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against own required fields and any inherited required
	// fields from allOf parents that are not flattened into this struct. Only keys
	// that map to struct fields are passed to the strict decoder.
	requiredProperties := []string{
		"requireTest",
	}

	requiredNullableProperties := map[string]bool{
		"requireTest": false,
	}

	allowedJsonKeys := []string{
		"promotion",
		"requireTest",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if value == nil && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	var filteredData []byte
	filteredProperties := make(map[string]interface{})
	for _, allowedKey := range allowedJsonKeys {
		if value, exists := allProperties[allowedKey]; exists {
			filteredProperties[allowedKey] = value
		}
	}

	filteredData, err = json.Marshal(filteredProperties)
	if err != nil {
		return err
	}

	varSpecialInfo := _SpecialInfo{}

	decoder := json.NewDecoder(bytes.NewReader(filteredData))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpecialInfo)

	if err != nil {
		return err
	}

	*o = SpecialInfo(varSpecialInfo)

	return nil
}

// AssertSpecialInfoRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertSpecialInfoRequired(obj SpecialInfo) error {
	return nil
}

// AssertSpecialInfoConstraints checks if the values respects the defined constraints
func AssertSpecialInfoConstraints(obj SpecialInfo) error {
	return nil
}
