// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 */

package petstoreserver


import (
	"bytes"
	"encoding/json"
)



// Pet - A pet for sale in the pet store
type Pet struct {

	Id int64 `json:"id,omitempty"`

	Category *Category `json:"category,omitempty"`

	Name string `json:"name"`

	PhotoUrls *[]string `json:"photoUrls"`

	Tags *[]Tag `json:"tags,omitempty"`

	// pet status in the store
	// Deprecated
	Status string `json:"status,omitempty"`
}
type _Pet Pet

// UnmarshalJSON validates required property keys then unmarshals into Pet
func (o *Pet) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against own required fields and any inherited required
	// fields from allOf parents that are not flattened into this struct. Only keys
	// that map to struct fields are passed to the strict decoder.
	requiredProperties := []string{
		"name",
		"photoUrls",
	}

	requiredNullableProperties := map[string]bool{
		"name": false,
		"photoUrls": true,
	}

	allowedJsonKeys := []string{
		"id",
		"category",
		"name",
		"photoUrls",
		"tags",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if value == nil && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	var filteredData []byte
	filteredProperties := make(map[string]interface{})
	for _, allowedKey := range allowedJsonKeys {
		if value, exists := allProperties[allowedKey]; exists {
			filteredProperties[allowedKey] = value
		}
	}

	filteredData, err = json.Marshal(filteredProperties)
	if err != nil {
		return err
	}

	varPet := _Pet{}

	decoder := json.NewDecoder(bytes.NewReader(filteredData))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPet)

	if err != nil {
		return err
	}

	*o = Pet(varPet)

	return nil
}

// AssertPetRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertPetRequired(obj Pet) error {
	if obj.Category != nil {
		if err := AssertCategoryRequired(*obj.Category); err != nil {
			return err
		}
	}
	if obj.Tags != nil {
		for _, el := range *obj.Tags {
			if err := AssertTagRequired(el); err != nil {
				return err
			}
		}
	}
	return nil
}

// AssertPetConstraints checks if the values respects the defined constraints
func AssertPetConstraints(obj Pet) error {
    if obj.Category != nil {
     	if err := AssertCategoryConstraints(*obj.Category); err != nil {
     		return err
     	}
    }
    if obj.Tags != nil {
     	for _, el := range *obj.Tags {
     		if err := AssertTagConstraints(el); err != nil {
     			return err
     		}
     	}
    }
	return nil
}
