// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 */

package petstoreserver


import (
	"time"
	"bytes"
	"encoding/json"
)



type Order struct {

	PetId int64 `json:"petId,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	ShipDate time.Time `json:"shipDate,omitempty"`

	Id int64 `json:"id,omitempty"`

	// Order Status
	Status string `json:"status,omitempty"`

	Complete bool `json:"complete,omitempty"`

	Comment *string `json:"comment"`
}
type _Order Order

// UnmarshalJSON validates required property keys then unmarshals into Order
func (o *Order) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against own required fields and any inherited required
	// fields from allOf parents that are not flattened into this struct. Only keys
	// that map to struct fields are passed to the strict decoder.
	requiredProperties := []string{
		"comment",
		"requireTest",
	}

	requiredNullableProperties := map[string]bool{
		"comment": true,
		"requireTest": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if value == nil && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	var filteredData []byte
	// Parent struct fields are embedded; the strict decoder already knows them.
	filteredData, err = json.Marshal(allProperties)
	if err != nil {
		return err
	}

	varOrder := _Order{}

	decoder := json.NewDecoder(bytes.NewReader(filteredData))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrder)

	if err != nil {
		return err
	}

	*o = Order(varOrder)

	return nil
}

// AssertOrderRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertOrderRequired(obj Order) error {
	return nil
}

// AssertOrderConstraints checks if the values respects the defined constraints
func AssertOrderConstraints(obj Order) error {
	return nil
}
