// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 */

package petstoreserver


import (
	"bytes"
	"encoding/json"
)



// UserNullable - A User who is purchasing from the pet store
type UserNullable struct {

	Id int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	Phone *string `json:"phone,omitempty"`

	// User Status
	UserStatus int32 `json:"userStatus,omitempty"`

	// An array 1-deep.
	DeepSliceModel *[][][]Tag `json:"deepSliceModel"`

	// An array 1-deep.
	DeepSliceMap [][]AnObject `json:"deepSliceMap,omitempty"`
}
type _UserNullable UserNullable

// UnmarshalJSON validates required property keys then unmarshals into UserNullable
func (o *UserNullable) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against own required fields and any inherited required
	// fields from allOf parents that are not flattened into this struct. Only keys
	// that map to struct fields are passed to the strict decoder.
	requiredProperties := []string{
		"deepSliceModel",
	}

	requiredNullableProperties := map[string]bool{
		"deepSliceModel": true,
	}

	allowedJsonKeys := []string{
		"id",
		"username",
		"firstName",
		"lastName",
		"email",
		"password",
		"phone",
		"userStatus",
		"deepSliceModel",
		"deepSliceMap",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if value == nil && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	var filteredData []byte
	filteredProperties := make(map[string]interface{})
	for _, allowedKey := range allowedJsonKeys {
		if value, exists := allProperties[allowedKey]; exists {
			filteredProperties[allowedKey] = value
		}
	}

	filteredData, err = json.Marshal(filteredProperties)
	if err != nil {
		return err
	}

	varUserNullable := _UserNullable{}

	decoder := json.NewDecoder(bytes.NewReader(filteredData))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserNullable)

	if err != nil {
		return err
	}

	*o = UserNullable(varUserNullable)

	return nil
}

// AssertUserNullableRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertUserNullableRequired(obj UserNullable) error {
	if obj.DeepSliceModel != nil {
		if err := AssertRecurseInterfaceRequired(*obj.DeepSliceModel, AssertTagRequired); err != nil {
			return err
		}
	}
	if err := AssertRecurseInterfaceRequired(obj.DeepSliceMap, AssertAnObjectRequired); err != nil {
		return err
	}
	return nil
}

// AssertUserNullableConstraints checks if the values respects the defined constraints
func AssertUserNullableConstraints(obj UserNullable) error {
    if obj.DeepSliceModel != nil {
     	if err := AssertRecurseInterfaceRequired(*obj.DeepSliceModel, AssertTagConstraints); err != nil {
     		return err
     	}
    }
	if err := AssertRecurseInterfaceRequired(obj.DeepSliceMap, AssertAnObjectConstraints); err != nil {
		return err
	}
	return nil
}
