// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Test - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package petstoreserver

import (
	"bytes"
	"encoding/json"
	"errors"
)

type TestObject struct {
	N int32 `json:"n"`
}

type _TestObject TestObject

// UnmarshalJSON validates required property keys then unmarshals into TestObject
func (o *TestObject) UnmarshalJSON(data []byte) (err error) {
	requiredProperties := []string{
		"n",
	}

	requiredNullableProperties := map[string]bool{
		"n": false,
	}

	allowedJsonKeys := []string{
		"n",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if value == nil && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	var filteredData []byte
	filteredProperties := make(map[string]interface{})
	for _, allowedKey := range allowedJsonKeys {
		if value, exists := allProperties[allowedKey]; exists {
			filteredProperties[allowedKey] = value
		}
	}

	filteredData, err = json.Marshal(filteredProperties)
	if err != nil {
		return err
	}

	varTestObject := _TestObject{}

	decoder := json.NewDecoder(bytes.NewReader(filteredData))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTestObject)

	if err != nil {
		return err
	}

	*o = TestObject(varTestObject)

	return nil
}

// AssertTestObjectRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertTestObjectRequired(obj TestObject) error {
	return nil
}

// AssertTestObjectConstraints checks if the values respects the defined constraints
func AssertTestObjectConstraints(obj TestObject) error {
	if obj.N < 0 {
		return &ParsingError{Param: "N", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
